<a href="https://colab.research.google.com/github/karthik-thatipelly/PyTorch_Coursework/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar

scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][2][1]

tensor(4)

### Random Tensors

In [ ]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8006, 0.5195, 0.6565, 0.0169],
        [0.4981, 0.2015, 0.0194, 0.9229],
        [0.8414, 0.2669, 0.9903, 0.3737]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor1 = torch.rand(2,3,4)
random_tensor1

tensor([[[0.8349, 0.4396, 0.4469, 0.3746],
         [0.2412, 0.0025, 0.4914, 0.5398],
         [0.8480, 0.3321, 0.8690, 0.0453]],

        [[0.7866, 0.7139, 0.9427, 0.5333],
         [0.2119, 0.1201, 0.5665, 0.0698],
         [0.8437, 0.8402, 0.0655, 0.5899]]])

In [ ]:
print(random_tensor1.ndim)
print(random_tensor1.shape)

3
torch.Size([2, 3, 4])


In [ ]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channels
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
random_image_size_tensor1 = torch.rand(size = (3, 224, 224)) # color channels, height, width
random_image_size_tensor1.ndim, random_image_size_tensor1.shape

(3, torch.Size([3, 224, 224]))

## Zeros and Ones

In [ ]:
# Create a tensor of all zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros * random_tensor, ones * random_tensor1

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[[0.8349, 0.4396, 0.4469, 0.3746],
          [0.2412, 0.0025, 0.4914, 0.5398],
          [0.8480, 0.3321, 0.8690, 0.0453]],
 
         [[0.7866, 0.7139, 0.9427, 0.5333],
          [0.2119, 0.1201, 0.5665, 0.0698],
          [0.8437, 0.8402, 0.0655, 0.5899]]]))

## Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()

one_to_ten = torch.arange(start=1, end = 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 4.0, 5.0],
                               dtype = None,   #what datatype is tensor
                               device=None,   #what device is our tensor on (cpu or gpu)
                               requires_grad=False)
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 16., 25.])

In [ ]:
int_32_tensor= torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 24., 45.])

In [ ]:
#Sometimes we may get errors when multiplying tensors of different dtypes

## Manipulating Tensors

### Tensor Operations include:

* Addition
* Subtraction
* Division
* Multiplication (element-wise)
* Matrix multiplication


In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
tensor + 10   # addition

tensor([11, 12, 13])

In [ ]:
tensor * 10  #multiplication

tensor([10, 20, 30])

In [ ]:
tensor - 10 # subtraction

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

In [ ]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(14)

# How to handle shape errors:

* Transpose any 1 matrix

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,11],
                         [12,14]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  31,  40],
        [ 53,  71,  92],
        [ 83, 111, 144]])

## Tensor Aggregators (min, max, mean etc)

In [ ]:
x = torch.arange(0 , 100 , 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### argmin and argmax

It means positional min and max

In [ ]:
y = torch.arange(1, 100, 10)
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
y.argmin()

tensor(0)

In [ ]:
y[0]

tensor(1)

In [ ]:
y.argmax()

tensor(9)

In [ ]:
y[9]

tensor(91)

### reshaping, viewing, stacking, squeezing, unsqueezing, permuting etc

In [ ]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Change the view

z= x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim = 0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Squeeze and unsqueeze

# torch.squeeze() will remocve all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

# Remove extra dimensions  from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)
print(x_squeezed.shape)

previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
previous shape: torch.Size([1, 9])
tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specifi dimension

print(x_squeezed, x_squeezed.shape)
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])


(tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
# torch.permute - rearranges the dimensions of target tensor in a specified order

x_original= torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0>1, 1>2, 2>0
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## Pytorch and Numpy

In [ ]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Check GPU access with PyTorch

torch.cuda.is_available()

True

In [ ]:
#Set device Type

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

In [ ]:
# creating a tensor and putting it on the GPU

tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

#Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Moving tensors back to the CPU

# tensor_on_gpu.numpy()     - gets errored out
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])